schema-version = "1.10.0"

[install]
git.pkg-path = "git"
gh.pkg-path = "gh"
fh.pkg-path = "fh"
direnv.pkg-path = "direnv"
jq.pkg-path = "jq"
ripgrep.pkg-path = "ripgrep"
fd.pkg-path = "fd"
bat.pkg-path = "bat"
eza.pkg-path = "eza"
nix.pkg-path = "nix"
nixd.pkg-path = "nixd"
nixfmt-rfc-style.pkg-path = "nixfmt-rfc-style"
deadnix.pkg-path = "deadnix"
statix.pkg-path = "statix"
nix-tree.pkg-path = "nix-tree"
openssh.pkg-path = "openssh"
pass.pkg-path = "pass"
gnupg.pkg-path = "gnupg"
ventoy.pkg-path = "ventoy"
libguestfs-with-appliance.pkg-path = "libguestfs-with-appliance"
gnutar.pkg-path = "gnutar"
gzip.pkg-path = "gzip"
findutils.pkg-path = "findutils"
tree.pkg-path = "tree"
util-linux.pkg-path = "util-linux"
squashfsTools.pkg-path = "squashfsTools"
file.pkg-path = "file"

[vars]
WORKSPACE_REPO = "nix-keys"

[hook]
on-activate = '''
  export REPO_ROOT="$FLOX_ENV_PROJECT"
  export PASSWORD_STORE_DIR="$FLOX_ENV_PROJECT/private"
'''

[profile]
common = """
  alias key-public-tree='tree public'
  alias key-private-tree='tree private'
  alias key-list='find public -type f -name \"*.pub\" | sort'
  alias check='nix flake check --no-build'
  alias fmt='nixfmt .'
  alias lint-deadcode='deadnix .'
  alias lint-patterns='statix check .'
  alias lint-patterns-fix='statix fix .'
  alias show='nix flake show'
"""

[options]
systems = ["x86_64-linux"]
allow.unfree = true
